apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:          # Contenedores que se ejecutarán en el pod
      - name: postgres # Nombre del contenedor
        image: postgres:15-alpine # Imagen de Docker a usar
        env:
        - name: POSTGRES_DB
          value: demo
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432 # Puerto en el que el contenedor escucha
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data # Ruta donde se montará el volumen
      volumes:
      - name: pgdata
        emptyDir: {} # Volumen temporal que se eliminará al eliminar el pod