apiVersion: v1
kind: Service
metadata:
  name: springboot-api-service # Nombre del servicio, usado para referenciarlo dentro del clúster
spec:
  type: NodePort # Tipo de servicio, accesible desde fuera del clúster
  selector:
    app: springboot-api # Selecciona los pods con la etiqueta app: springboot-api
  ports:
  - port: 8080 # Puerto que el servicio utilizará dentro del clúster
    targetPort: 8080 # Puerto al que se redirigirá el tráfico en los pods
    protocol: TCP # Protocolo utilizado
    nodePort: 30080 # Puerto en el nodo del clúster para acceder al servicio desde fuera  